#!/bin/bash

set -e -u -x

pushd glide
  git_summary=$(git describe --tags --dirty --always)
  go_version=$(go version)

  GOOS="linux" GOARCH="amd64" go build -ldflags="-X 'main.gitSummary=$git_summary' -X 'main.goVersion=$go_version'" -o ../build/vulcan_linux_amd64 main.go
popd
