#!/bin/bash

set -e -u -x

# glide installs golang depedencies attempting to use a cache from s3
# but falling back to running a glide install and writing that result
# to s3 for next time.
#
# glide uses the "hash" value from glide.lock as the cache key.
#
# inputs: src/glide.lock
# outputs: cache/cache.tar.gz
# env vars: 
#   S3_BUCKET
#   S3_PATH
#   AWS_ACCESS_KEY_ID
#   AWS_SECRET_ACCESS_KEY

hash=$(cat src/glide.lock | shyaml get-value hash)
s3_uri="s3://$S3_BUCKET$S3_PATH/$hash.tar.gz"

if ! aws s3 cp $s3_uri cache/cache.tar.gz &> /dev/null; then
  pushd src
    glide --home ../glide install --strip-vendor
  popd
  ls -alh glide/cache
  tar czf cache/cache.tar.gz -C glide/ .
  aws s3 cp cache/cache.tar.gz $s3_uri
fi
