---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.3

inputs:
- name: src
- name: glide

outputs:
- name: build

run:
  path: src/ci/scripts/build
